/* ============================================
   本 (HON) — ARCHIVE CATALOG DATA
   Real Japanese print media from the collector's own
   physical collection, photographed front and back.
   coverBg/coverFg/coverAccent are used as a fallback
   border/frame treatment and for the item-page detail
   view; coverImage/backImage are the real photographs.
   ============================================ */

const HON_CATALOG = [
  {
    id: "burst-vol15",
    title: "BURST",
    issue: "Vol.15",
    era: "1998",
    genre: "Tattoo & Subculture",
    call: "本 · TS · 98-015",
    copies: 1,
    coverBg: "#0a0a0a",
    coverFg: "#faf9f4",
    coverAccent: "#3a6ea5",
    coverImage: "images/covers/BURST-vol15-front.jpg",
    backImage: "images/covers/BURST-vol15-back.jpg",
    desc: "A reader-submitted portrait series of Tokyo's young outsiders, bōsōzoku bikers, tattooed wrestlers, hardcore punks, runs alongside dispatches from tattoo conventions around Japan in this July 1998 issue.",
  },
  {
    id: "burst-vol16",
    title: "BURST",
    issue: "Vol.16",
    era: "1998",
    genre: "Tattoo & Subculture",
    call: "本 · TS · 98-016",
    copies: 1,
    coverBg: "#1a1a1a",
    coverFg: "#d4af37",
    coverAccent: "#c8102e",
    coverImage: "images/covers/BURST-vol16-front.jpg",
    backImage: "images/covers/BURST-vol16-back.jpg",
    desc: "Four members of a Tokyo punk crew appear on the cover of an issue built around a Che Guevara retrospective, interviews with the band circling Shinjuku's live houses, and tattoo event reports from across Japan.",
  },
  {
    id: "burst-vol17",
    title: "BURST",
    subtitle: "Topless Government",
    issue: "Vol.17",
    era: "1998",
    genre: "Tattoo & Subculture",
    call: "本 · TS · 98-017",
    copies: 1,
    coverBg: "#faf9f4",
    coverFg: "#c8102e",
    coverAccent: "#0a0a0a",
    coverImage: "images/covers/BURST-vol17-front.jpg",
    backImage: "images/covers/BURST-vol17-back.jpg",
    desc: "A cover feature on a fully tattooed model runs alongside a garage-rock compilation insert, part of BURST's ongoing coverage of Japan's tattoo culture years before it had mainstream visibility.",
  },
  {
    id: "burst-vol24",
    title: "BURST",
    issue: "Vol.24",
    era: "1999",
    genre: "Tattoo & Subculture",
    call: "本 · TS · 99-024",
    copies: 1,
    coverBg: "#3a4a5a",
    coverFg: "#faf9f4",
    coverAccent: "#c8102e",
    coverImage: "images/covers/BURST-vol24-front.jpg",
    backImage: "images/covers/BURST-vol24-back.jpg",
    desc: "An investigative feature on wild-growing cannabis in Hokkaido shares this December 1999 issue with coverage of a European motorcycle leather jacket convention and a Tokyo tattoo expo.",
  },
  {
    id: "burst-vol41",
    title: "BURST",
    issue: "Vol.41",
    era: "2001",
    genre: "Tattoo & Subculture",
    call: "本 · TS · 01-041",
    copies: 1,
    coverBg: "#8a8a8a",
    coverFg: "#e91e8c",
    coverAccent: "#c8102e",
    coverImage: "images/covers/BURST-vol41-front.jpg",
    backImage: "images/covers/BURST-vol41-back.jpg",
    desc: "A cover feature on a photographer's dispatch from Zapatista territory in Chiapas runs alongside an interview with musician Phew, a rare collision of BURST's tabloid sensationalism with war photography.",
  },
  {
    id: "burst-vol47",
    title: "BURST",
    issue: "Vol.47",
    era: "2001",
    genre: "Tattoo & Subculture",
    call: "本 · TS · 01-047",
    copies: 1,
    coverBg: "#5a6b3a",
    coverFg: "#faf9f4",
    coverAccent: "#d68a1a",
    coverImage: "images/covers/BURST-vol47-front.jpg",
    backImage: "images/covers/BURST-vol47-back.jpg",
    desc: "A home-growing guide reprinted from High Times, with an interview with its editor Steven Hager, anchors this November 2001 issue alongside a retrospective on Japan's early rave and trance scene.",
  },
  {
    id: "fruits-no92",
    title: "FRUITS",
    issue: "No.92",
    era: "2005",
    genre: "Street Fashion",
    call: "本 · SF · 05-092",
    copies: 1,
    coverBg: "#0f4c81",
    coverFg: "#faf9f4",
    coverAccent: "#e91e8c",
    coverImage: "images/covers/FRUITS-no92-front.jpg",
    backImage: "images/covers/FRUITS-no92-back.jpg",
    desc: "A single BMX-riding street snap from Harajuku, shot in FRUITS' signature format of one outfit against one backdrop with almost no text, the magazine that made Shoichi Aoki's street photography its own genre.",
  },
  {
    id: "street-no182",
    title: "STREET",
    issue: "No.182",
    era: "2006",
    genre: "Street Fashion",
    call: "本 · SF · 06-182",
    copies: 1,
    coverBg: "#0a3d3d",
    coverFg: "#faf9f4",
    coverAccent: "#ff4d6d",
    coverImage: "images/covers/STREET-no182-front.jpg",
    backImage: "images/covers/STREET-no182-back.jpg",
    desc: "A group portrait of London and Berlin club kids for STREET's recurring project setting Tokyo style against other capitals' scenes, Shoichi Aoki's parallel magazine alongside FRUITS.",
  },
  {
    id: "tune-no86",
    title: "TUNE",
    issue: "No.86",
    era: "2011",
    genre: "Street Fashion",
    call: "本 · SF · 11-086",
    copies: 1,
    coverBg: "#b91c1c",
    coverFg: "#faf9f4",
    coverAccent: "#0a0a0a",
    coverImage: "images/covers/TUNE-no86-front.jpg",
    backImage: "images/covers/TUNE-no86-back.jpg",
    desc: "A Harajuku street-style snap on the cover pairs with an ad for Osaka label monomania on the reverse, typical of TUNE's format mixing candid photography with brand advertising.",
  },
  {
    id: "lightning-vol28",
    title: "別冊Lightning",
    subtitle: "Denim Style Book 2",
    issue: "Vol.28 (Bessatsu)",
    era: "2006",
    genre: "Heritage Menswear",
    call: "本 · HM · 06-028",
    copies: 1,
    coverBg: "#1e5aa8",
    coverFg: "#faf9f4",
    coverAccent: "#e8531e",
    coverImage: "images/covers/Lightning-vol28-front.jpg",
    backImage: "images/covers/Lightning-vol28-back.jpg",
    desc: "A themed denim mook under the Lightning banner, cataloguing vintage jeans construction, with a Yamane repro-denim advertisement on the back cover. Part of Lightning's separately numbered Bessatsu supplement series, not the main monthly run.",
  },
  {
    id: "lightning-vol35",
    title: "別冊Lightning",
    subtitle: "Coffee Style Book",
    issue: "Vol.35 (Bessatsu)",
    era: "2007",
    genre: "Heritage Menswear",
    call: "本 · HM · 07-035",
    copies: 1,
    coverBg: "#5a3a28",
    coverFg: "#faf9f4",
    coverAccent: "#e8531e",
    coverImage: "images/covers/Lightning-vol35-front.jpg",
    backImage: "images/covers/Lightning-vol35-back.jpg",
    desc: "A themed supplement pairing vintage espresso equipment and mug collecting with a Suntory BOSS canned-coffee advertisement on the reverse. Part of the same Bessatsu Lightning mook series as the Denim Style Book.",
  },
  {
    id: "lightning-vol354",
    title: "Lightning",
    subtitle: "Cool Used Clothing",
    issue: "Vol.354",
    era: "2023",
    genre: "Heritage Menswear",
    call: "本 · HM · 23-354",
    copies: 1,
    coverBg: "#f0ede2",
    coverFg: "#2d6a4f",
    coverAccent: "#e8a13a",
    coverImage: "images/covers/Lightning-vol354-front.jpg",
    backImage: "images/covers/Lightning-vol354-back.jpg",
    desc: "A worn pair of vintage Levi's anchors this issue's guide to loose, broken-in secondhand clothing, with a Schott NYC 110th-anniversary advertisement on the back.",
  },
  {
    id: "lightning-vol360",
    title: "Lightning",
    subtitle: "Mid-Century",
    issue: "Vol.360",
    era: "2024",
    genre: "Heritage Menswear",
    call: "本 · HM · 24-360",
    copies: 1,
    coverBg: "#f0ede2",
    coverFg: "#d63a8c",
    coverAccent: "#3a6ea5",
    coverImage: "images/covers/Lightning-vol360-front.jpg",
    backImage: "images/covers/Lightning-vol360-back.jpg",
    desc: "An Eames fiberglass rocking chair fronts a mid-century furniture and design issue, backed by an advertisement for Unkochan, an Osaka-area vintage furniture retailer.",
  },
  {
    id: "lightning-vol367",
    title: "Lightning",
    subtitle: "Work Wear",
    issue: "Vol.367",
    era: "2024",
    genre: "Heritage Menswear",
    call: "本 · HM · 24-367",
    copies: 1,
    coverBg: "#e8c934",
    coverFg: "#0a0a0a",
    coverAccent: "#c8102e",
    coverImage: "images/covers/Lightning-vol367-front.jpg",
    backImage: "images/covers/Lightning-vol367-back.jpg",
    desc: "A well-worn denim chore coat fronts a workwear-focused issue tracing the garment's roots, paired with a Red Wing boots advertisement on the reverse.",
  },
  {
    id: "lightning-vol372",
    title: "Lightning",
    subtitle: "Focus on Sweat Shirts",
    issue: "Vol.372",
    era: "2025",
    genre: "Heritage Menswear",
    call: "本 · HM · 25-372",
    copies: 1,
    coverBg: "#2d4a3a",
    coverFg: "#e8a13a",
    coverAccent: "#faf9f4",
    coverImage: "images/covers/Lightning-vol372-front.jpg",
    backImage: "images/covers/Lightning-vol372-back.jpg",
    desc: "A single vintage sweatshirt on a hanger fronts an issue tracing the garment from military surplus to street-style staple, with a Wesco motorcycle boots advertisement on the back.",
  },
  {
    id: "lightning-vol378",
    title: "Lightning",
    subtitle: "Cowboy Style Forever",
    issue: "Vol.378",
    era: "2025",
    genre: "Heritage Menswear",
    call: "本 · HM · 25-378",
    copies: 1,
    coverBg: "#faf9f4",
    coverFg: "#e8531e",
    coverAccent: "#0a0a0a",
    coverImage: "images/covers/Lightning-vol378-front.jpg",
    backImage: "images/covers/Lightning-vol378-back.jpg",
    desc: "A rodeo rider mid-bronc fronts Lightning's cowboy workwear issue, backed by another Wesco leather motorcycle boots advertisement.",
  },
  {
    id: "xbox360-2009",
    title: "ファミ通Xbox360",
    subtitle: "Famitsu Xbox 360",
    issue: "Sept. 2009",
    era: "2009",
    genre: "Gaming Culture",
    call: "本 · GM · 09-001",
    copies: 1,
    coverBg: "#0a0a0a",
    coverFg: "#e8531e",
    coverAccent: "#faf9f4",
    coverImage: "images/covers/Xbox360-2009-front.jpg",
    backImage: "images/covers/Xbox360-2009-back.jpg",
    desc: "A Japanese gaming magazine's coverage of the domestic launch of Gears of War 2, with a promotional back-cover feature for the visual novel Steins;Gate ahead of its October 2009 release.",
  },
];
